# Generated by Django 3.1.3 on 2020-11-27 17:47

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions_api', '0003_auto_20201127_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptions',
            name='timestamp',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now_add=True),
        ),
    ]
